export const jobList = {
    null: {label_fr: "Tous", icon_number: '000'},
    "ACN": {label_fr: "Arcaniste", icon_number: '026'},
    "ADV": {label_fr: "Toutes les classes", icon_number: '000'},
    "ALC": {label_fr: "Alchimiste", icon_number: '014'},
    "ARC": {label_fr: "Archer", icon_number: '005'},
    "ARM": {label_fr: "Armurier", icon_number: '010'},
    "AST": {label_fr: "Astromancien", icon_number: '033'},
    "BLM": {label_fr: "Mage  Noire", icon_number: '025'},
    "BLU": {label_fr: "Mage Bleu", icon_number: '036'},
    "BRD": {label_fr: "Barde", icon_number: '023'},
    "BSM": {label_fr: "Forgeron", icon_number: '009'},
    "BTN": {label_fr: "Botaniste", icon_number: '017'},
    "CNJ": {label_fr: "Elementaliste", icon_number: '006'},
    "CRP": {label_fr: "Menuisier", icon_number: '008'},
    "CUL": {label_fr: "Cuisinier", icon_number: '015'},
    "DNC": {label_fr: "Danseur", icon_number: '038'},
    "DRG": {label_fr: "Chevalier Dragon", icon_number: '022'},
    "DRK": {label_fr: "Chevalier Noir", icon_number: '032'},
    "FSH": {label_fr: "Pêcheur", icon_number: '018'},
    "GLA": {label_fr: "Gladiateur", icon_number: '001'},
    "GNB": {label_fr: "Pistosabreur", icon_number: '037'},
    "GSM": {label_fr: "Orfèvre", icon_number: '011'},
    "LNC": {label_fr: "Maître d'Hast", icon_number: '004'},
    "LTW": {label_fr: "Tanneur", icon_number: '012'},
    "MCH": {label_fr: "Machiniste", icon_number: '031'},
    "MIN": {label_fr: "Mineur", icon_number: '016'},
    "MNK": {label_fr: "Moine", icon_number: '020'},
    "MRD": {label_fr: "Maraudeur", icon_number: '003'},
    "NIN": {label_fr: "Ninja", icon_number: '030'},
    "PGL": {label_fr: "Pugiliste", icon_number: '002'},
    "PLD": {label_fr: "Paladin", icon_number: '019'},
    "RDM": {label_fr: "Mage Rouge", icon_number: '035'},
    "ROG": {label_fr: "Surineur", icon_number: '029'},
    "SAM": {label_fr: "Samouraï", icon_number: '034'},
    "SCH": {label_fr: "Erudit", icon_number: '028'},
    "SMN": {label_fr: "Invocateur", icon_number: '027'},
    "THM": {label_fr: "Occultiste", icon_number: '007'},
    "WAR": {label_fr: "Guerrier", icon_number: '021'},
    "WHM": {label_fr: "Mage Blanc", icon_number: '024'},
    "WVR": {label_fr: "Couturier", icon_number: '013'}
}


